Dispatcher:
  Allocation:
     qps: 20
     burst: 40
  Pod:
     qps: 20
     burst: 40
     contentType: application/vnd.kubernetes.protobuf
Distributor:
  Allocation:
     qps: 20
     burst: 40
  Pod:
     qps: 20
     burst: 40
     contentType: application/vnd.kubernetes.protobuf
Scheduler:
  Allocation:
     qps: 20
     burst: 40
  Pod:
     qps: 20
     burst: 40
     contentType: application/vnd.kubernetes.protobuf
