Dispatcher:
  Allocation:
     qps: 500
     burst: 1000
  Pod:
     qps: 500
     burst: 1000
     contentType: application/vnd.kubernetes.protobuf
Distributor:
  Allocation:
     qps: 500
     burst: 1000
  Pod:
     qps: 500
     burst: 1000
     contentType: application/vnd.kubernetes.protobuf
Scheduler:
  Allocation:
     qps: 500
     burst: 1000
  Pod:
     qps: 500
     burst: 1000
     contentType: application/vnd.kubernetes.protobuf
