Dispatcher:
  qps: 20
  burst: 40
  contentTiype: application/vnd.kubernetes.protobuf
Distributor:
  qps: 20
  burst: 40
  contentTiype: application/vnd.kubernetes.protobuf
Scheduler:
  qps: 20
  burst: 40
  contentTiype: application/vnd.kubernetes.protobuf

