// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "globalscheduler/pkg/apis/clientset/versioned/typed/clusters/v1"

	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeGlobalschedulerV1 struct {
	*testing.Fake
}

func (c *FakeGlobalschedulerV1) Clusters(namespace string) v1.ClusterInterface {
	return &FakeClusters{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeGlobalschedulerV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
