// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cluster.proto

package proto // import "k8s.io/kubernetes/globalscheduler/grpc/cluster/proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReturnMessageClusterProfile_CodeType int32

const (
	ReturnMessageClusterProfile_Error ReturnMessageClusterProfile_CodeType = 0
	ReturnMessageClusterProfile_OK    ReturnMessageClusterProfile_CodeType = 1
)

var ReturnMessageClusterProfile_CodeType_name = map[int32]string{
	0: "Error",
	1: "OK",
}
var ReturnMessageClusterProfile_CodeType_value = map[string]int32{
	"Error": 0,
	"OK":    1,
}

func (x ReturnMessageClusterProfile_CodeType) String() string {
	return proto.EnumName(ReturnMessageClusterProfile_CodeType_name, int32(x))
}
func (ReturnMessageClusterProfile_CodeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cluster_f471dfbba0a766f3, []int{1, 0}
}

// message from ClusterController to ResourceCollector
type ClusterProfile struct {
	ClusterNameSpace     string                          `protobuf:"bytes,1,opt,name=ClusterNameSpace,proto3" json:"ClusterNameSpace,omitempty"`
	ClusterName          string                          `protobuf:"bytes,2,opt,name=ClusterName,proto3" json:"ClusterName,omitempty"`
	ClusterSpec          *ClusterProfile_ClusterSpecInfo `protobuf:"bytes,3,opt,name=ClusterSpec,proto3" json:"ClusterSpec,omitempty"`
	ClusterStatus        string                          `protobuf:"bytes,4,opt,name=ClusterStatus,proto3" json:"ClusterStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ClusterProfile) Reset()         { *m = ClusterProfile{} }
func (m *ClusterProfile) String() string { return proto.CompactTextString(m) }
func (*ClusterProfile) ProtoMessage()    {}
func (*ClusterProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_f471dfbba0a766f3, []int{0}
}
func (m *ClusterProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterProfile.Unmarshal(m, b)
}
func (m *ClusterProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterProfile.Marshal(b, m, deterministic)
}
func (dst *ClusterProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterProfile.Merge(dst, src)
}
func (m *ClusterProfile) XXX_Size() int {
	return xxx_messageInfo_ClusterProfile.Size(m)
}
func (m *ClusterProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterProfile.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterProfile proto.InternalMessageInfo

func (m *ClusterProfile) GetClusterNameSpace() string {
	if m != nil {
		return m.ClusterNameSpace
	}
	return ""
}

func (m *ClusterProfile) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *ClusterProfile) GetClusterSpec() *ClusterProfile_ClusterSpecInfo {
	if m != nil {
		return m.ClusterSpec
	}
	return nil
}

func (m *ClusterProfile) GetClusterStatus() string {
	if m != nil {
		return m.ClusterStatus
	}
	return ""
}

type ClusterProfile_ClusterSpecInfo struct {
	ClusterIpAddress     string                                          `protobuf:"bytes,1,opt,name=ClusterIpAddress,proto3" json:"ClusterIpAddress,omitempty"`
	GeoLocation          *ClusterProfile_ClusterSpecInfo_GeoLocationInfo `protobuf:"bytes,2,opt,name=GeoLocation,proto3" json:"GeoLocation,omitempty"`
	Region               *ClusterProfile_ClusterSpecInfo_RegionInfo      `protobuf:"bytes,3,opt,name=Region,proto3" json:"Region,omitempty"`
	Operator             *ClusterProfile_ClusterSpecInfo_OperatorInfo    `protobuf:"bytes,4,opt,name=Operator,proto3" json:"Operator,omitempty"`
	Flavor               []*ClusterProfile_ClusterSpecInfo_FlavorInfo    `protobuf:"bytes,5,rep,name=Flavor,proto3" json:"Flavor,omitempty"`
	Storage              []*ClusterProfile_ClusterSpecInfo_StorageInfo   `protobuf:"bytes,6,rep,name=Storage,proto3" json:"Storage,omitempty"`
	EipCapacity          int64                                           `protobuf:"varint,7,opt,name=EipCapacity,proto3" json:"EipCapacity,omitempty"`
	CPUCapacity          int64                                           `protobuf:"varint,8,opt,name=CPUCapacity,proto3" json:"CPUCapacity,omitempty"`
	MemCapacity          int64                                           `protobuf:"varint,9,opt,name=MemCapacity,proto3" json:"MemCapacity,omitempty"`
	ServerPrice          int64                                           `protobuf:"varint,10,opt,name=ServerPrice,proto3" json:"ServerPrice,omitempty"`
	HomeScheduler        string                                          `protobuf:"bytes,11,opt,name=HomeScheduler,proto3" json:"HomeScheduler,omitempty"`
	HomeDispatcher       string                                          `protobuf:"bytes,12,opt,name=HomeDispatcher,proto3" json:"HomeDispatcher,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                        `json:"-"`
	XXX_unrecognized     []byte                                          `json:"-"`
	XXX_sizecache        int32                                           `json:"-"`
}

func (m *ClusterProfile_ClusterSpecInfo) Reset()         { *m = ClusterProfile_ClusterSpecInfo{} }
func (m *ClusterProfile_ClusterSpecInfo) String() string { return proto.CompactTextString(m) }
func (*ClusterProfile_ClusterSpecInfo) ProtoMessage()    {}
func (*ClusterProfile_ClusterSpecInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_f471dfbba0a766f3, []int{0, 0}
}
func (m *ClusterProfile_ClusterSpecInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterProfile_ClusterSpecInfo.Unmarshal(m, b)
}
func (m *ClusterProfile_ClusterSpecInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterProfile_ClusterSpecInfo.Marshal(b, m, deterministic)
}
func (dst *ClusterProfile_ClusterSpecInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterProfile_ClusterSpecInfo.Merge(dst, src)
}
func (m *ClusterProfile_ClusterSpecInfo) XXX_Size() int {
	return xxx_messageInfo_ClusterProfile_ClusterSpecInfo.Size(m)
}
func (m *ClusterProfile_ClusterSpecInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterProfile_ClusterSpecInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterProfile_ClusterSpecInfo proto.InternalMessageInfo

func (m *ClusterProfile_ClusterSpecInfo) GetClusterIpAddress() string {
	if m != nil {
		return m.ClusterIpAddress
	}
	return ""
}

func (m *ClusterProfile_ClusterSpecInfo) GetGeoLocation() *ClusterProfile_ClusterSpecInfo_GeoLocationInfo {
	if m != nil {
		return m.GeoLocation
	}
	return nil
}

func (m *ClusterProfile_ClusterSpecInfo) GetRegion() *ClusterProfile_ClusterSpecInfo_RegionInfo {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *ClusterProfile_ClusterSpecInfo) GetOperator() *ClusterProfile_ClusterSpecInfo_OperatorInfo {
	if m != nil {
		return m.Operator
	}
	return nil
}

func (m *ClusterProfile_ClusterSpecInfo) GetFlavor() []*ClusterProfile_ClusterSpecInfo_FlavorInfo {
	if m != nil {
		return m.Flavor
	}
	return nil
}

func (m *ClusterProfile_ClusterSpecInfo) GetStorage() []*ClusterProfile_ClusterSpecInfo_StorageInfo {
	if m != nil {
		return m.Storage
	}
	return nil
}

func (m *ClusterProfile_ClusterSpecInfo) GetEipCapacity() int64 {
	if m != nil {
		return m.EipCapacity
	}
	return 0
}

func (m *ClusterProfile_ClusterSpecInfo) GetCPUCapacity() int64 {
	if m != nil {
		return m.CPUCapacity
	}
	return 0
}

func (m *ClusterProfile_ClusterSpecInfo) GetMemCapacity() int64 {
	if m != nil {
		return m.MemCapacity
	}
	return 0
}

func (m *ClusterProfile_ClusterSpecInfo) GetServerPrice() int64 {
	if m != nil {
		return m.ServerPrice
	}
	return 0
}

func (m *ClusterProfile_ClusterSpecInfo) GetHomeScheduler() string {
	if m != nil {
		return m.HomeScheduler
	}
	return ""
}

func (m *ClusterProfile_ClusterSpecInfo) GetHomeDispatcher() string {
	if m != nil {
		return m.HomeDispatcher
	}
	return ""
}

type ClusterProfile_ClusterSpecInfo_GeoLocationInfo struct {
	City                 string   `protobuf:"bytes,1,opt,name=City,proto3" json:"City,omitempty"`
	Province             string   `protobuf:"bytes,2,opt,name=Province,proto3" json:"Province,omitempty"`
	Area                 string   `protobuf:"bytes,3,opt,name=Area,proto3" json:"Area,omitempty"`
	Country              string   `protobuf:"bytes,4,opt,name=Country,proto3" json:"Country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterProfile_ClusterSpecInfo_GeoLocationInfo) Reset() {
	*m = ClusterProfile_ClusterSpecInfo_GeoLocationInfo{}
}
func (m *ClusterProfile_ClusterSpecInfo_GeoLocationInfo) String() string {
	return proto.CompactTextString(m)
}
func (*ClusterProfile_ClusterSpecInfo_GeoLocationInfo) ProtoMessage() {}
func (*ClusterProfile_ClusterSpecInfo_GeoLocationInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_f471dfbba0a766f3, []int{0, 0, 0}
}
func (m *ClusterProfile_ClusterSpecInfo_GeoLocationInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterProfile_ClusterSpecInfo_GeoLocationInfo.Unmarshal(m, b)
}
func (m *ClusterProfile_ClusterSpecInfo_GeoLocationInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterProfile_ClusterSpecInfo_GeoLocationInfo.Marshal(b, m, deterministic)
}
func (dst *ClusterProfile_ClusterSpecInfo_GeoLocationInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterProfile_ClusterSpecInfo_GeoLocationInfo.Merge(dst, src)
}
func (m *ClusterProfile_ClusterSpecInfo_GeoLocationInfo) XXX_Size() int {
	return xxx_messageInfo_ClusterProfile_ClusterSpecInfo_GeoLocationInfo.Size(m)
}
func (m *ClusterProfile_ClusterSpecInfo_GeoLocationInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterProfile_ClusterSpecInfo_GeoLocationInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterProfile_ClusterSpecInfo_GeoLocationInfo proto.InternalMessageInfo

func (m *ClusterProfile_ClusterSpecInfo_GeoLocationInfo) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *ClusterProfile_ClusterSpecInfo_GeoLocationInfo) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *ClusterProfile_ClusterSpecInfo_GeoLocationInfo) GetArea() string {
	if m != nil {
		return m.Area
	}
	return ""
}

func (m *ClusterProfile_ClusterSpecInfo_GeoLocationInfo) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type ClusterProfile_ClusterSpecInfo_RegionInfo struct {
	Region               string   `protobuf:"bytes,1,opt,name=Region,proto3" json:"Region,omitempty"`
	AvailabilityZone     string   `protobuf:"bytes,2,opt,name=AvailabilityZone,proto3" json:"AvailabilityZone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterProfile_ClusterSpecInfo_RegionInfo) Reset() {
	*m = ClusterProfile_ClusterSpecInfo_RegionInfo{}
}
func (m *ClusterProfile_ClusterSpecInfo_RegionInfo) String() string { return proto.CompactTextString(m) }
func (*ClusterProfile_ClusterSpecInfo_RegionInfo) ProtoMessage()    {}
func (*ClusterProfile_ClusterSpecInfo_RegionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_f471dfbba0a766f3, []int{0, 0, 1}
}
func (m *ClusterProfile_ClusterSpecInfo_RegionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterProfile_ClusterSpecInfo_RegionInfo.Unmarshal(m, b)
}
func (m *ClusterProfile_ClusterSpecInfo_RegionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterProfile_ClusterSpecInfo_RegionInfo.Marshal(b, m, deterministic)
}
func (dst *ClusterProfile_ClusterSpecInfo_RegionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterProfile_ClusterSpecInfo_RegionInfo.Merge(dst, src)
}
func (m *ClusterProfile_ClusterSpecInfo_RegionInfo) XXX_Size() int {
	return xxx_messageInfo_ClusterProfile_ClusterSpecInfo_RegionInfo.Size(m)
}
func (m *ClusterProfile_ClusterSpecInfo_RegionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterProfile_ClusterSpecInfo_RegionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterProfile_ClusterSpecInfo_RegionInfo proto.InternalMessageInfo

func (m *ClusterProfile_ClusterSpecInfo_RegionInfo) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *ClusterProfile_ClusterSpecInfo_RegionInfo) GetAvailabilityZone() string {
	if m != nil {
		return m.AvailabilityZone
	}
	return ""
}

type ClusterProfile_ClusterSpecInfo_OperatorInfo struct {
	Operator             string   `protobuf:"bytes,1,opt,name=Operator,proto3" json:"Operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterProfile_ClusterSpecInfo_OperatorInfo) Reset() {
	*m = ClusterProfile_ClusterSpecInfo_OperatorInfo{}
}
func (m *ClusterProfile_ClusterSpecInfo_OperatorInfo) String() string {
	return proto.CompactTextString(m)
}
func (*ClusterProfile_ClusterSpecInfo_OperatorInfo) ProtoMessage() {}
func (*ClusterProfile_ClusterSpecInfo_OperatorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_f471dfbba0a766f3, []int{0, 0, 2}
}
func (m *ClusterProfile_ClusterSpecInfo_OperatorInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterProfile_ClusterSpecInfo_OperatorInfo.Unmarshal(m, b)
}
func (m *ClusterProfile_ClusterSpecInfo_OperatorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterProfile_ClusterSpecInfo_OperatorInfo.Marshal(b, m, deterministic)
}
func (dst *ClusterProfile_ClusterSpecInfo_OperatorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterProfile_ClusterSpecInfo_OperatorInfo.Merge(dst, src)
}
func (m *ClusterProfile_ClusterSpecInfo_OperatorInfo) XXX_Size() int {
	return xxx_messageInfo_ClusterProfile_ClusterSpecInfo_OperatorInfo.Size(m)
}
func (m *ClusterProfile_ClusterSpecInfo_OperatorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterProfile_ClusterSpecInfo_OperatorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterProfile_ClusterSpecInfo_OperatorInfo proto.InternalMessageInfo

func (m *ClusterProfile_ClusterSpecInfo_OperatorInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ClusterProfile_ClusterSpecInfo_FlavorInfo struct {
	FlavorID             string   `protobuf:"bytes,1,opt,name=FlavorID,proto3" json:"FlavorID,omitempty"`
	TotalCapacity        int64    `protobuf:"varint,2,opt,name=TotalCapacity,proto3" json:"TotalCapacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterProfile_ClusterSpecInfo_FlavorInfo) Reset() {
	*m = ClusterProfile_ClusterSpecInfo_FlavorInfo{}
}
func (m *ClusterProfile_ClusterSpecInfo_FlavorInfo) String() string { return proto.CompactTextString(m) }
func (*ClusterProfile_ClusterSpecInfo_FlavorInfo) ProtoMessage()    {}
func (*ClusterProfile_ClusterSpecInfo_FlavorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_f471dfbba0a766f3, []int{0, 0, 3}
}
func (m *ClusterProfile_ClusterSpecInfo_FlavorInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterProfile_ClusterSpecInfo_FlavorInfo.Unmarshal(m, b)
}
func (m *ClusterProfile_ClusterSpecInfo_FlavorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterProfile_ClusterSpecInfo_FlavorInfo.Marshal(b, m, deterministic)
}
func (dst *ClusterProfile_ClusterSpecInfo_FlavorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterProfile_ClusterSpecInfo_FlavorInfo.Merge(dst, src)
}
func (m *ClusterProfile_ClusterSpecInfo_FlavorInfo) XXX_Size() int {
	return xxx_messageInfo_ClusterProfile_ClusterSpecInfo_FlavorInfo.Size(m)
}
func (m *ClusterProfile_ClusterSpecInfo_FlavorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterProfile_ClusterSpecInfo_FlavorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterProfile_ClusterSpecInfo_FlavorInfo proto.InternalMessageInfo

func (m *ClusterProfile_ClusterSpecInfo_FlavorInfo) GetFlavorID() string {
	if m != nil {
		return m.FlavorID
	}
	return ""
}

func (m *ClusterProfile_ClusterSpecInfo_FlavorInfo) GetTotalCapacity() int64 {
	if m != nil {
		return m.TotalCapacity
	}
	return 0
}

type ClusterProfile_ClusterSpecInfo_StorageInfo struct {
	TypeID               string   `protobuf:"bytes,1,opt,name=TypeID,proto3" json:"TypeID,omitempty"`
	StorageCapacity      int64    `protobuf:"varint,2,opt,name=StorageCapacity,proto3" json:"StorageCapacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterProfile_ClusterSpecInfo_StorageInfo) Reset() {
	*m = ClusterProfile_ClusterSpecInfo_StorageInfo{}
}
func (m *ClusterProfile_ClusterSpecInfo_StorageInfo) String() string {
	return proto.CompactTextString(m)
}
func (*ClusterProfile_ClusterSpecInfo_StorageInfo) ProtoMessage() {}
func (*ClusterProfile_ClusterSpecInfo_StorageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_f471dfbba0a766f3, []int{0, 0, 4}
}
func (m *ClusterProfile_ClusterSpecInfo_StorageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterProfile_ClusterSpecInfo_StorageInfo.Unmarshal(m, b)
}
func (m *ClusterProfile_ClusterSpecInfo_StorageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterProfile_ClusterSpecInfo_StorageInfo.Marshal(b, m, deterministic)
}
func (dst *ClusterProfile_ClusterSpecInfo_StorageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterProfile_ClusterSpecInfo_StorageInfo.Merge(dst, src)
}
func (m *ClusterProfile_ClusterSpecInfo_StorageInfo) XXX_Size() int {
	return xxx_messageInfo_ClusterProfile_ClusterSpecInfo_StorageInfo.Size(m)
}
func (m *ClusterProfile_ClusterSpecInfo_StorageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterProfile_ClusterSpecInfo_StorageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterProfile_ClusterSpecInfo_StorageInfo proto.InternalMessageInfo

func (m *ClusterProfile_ClusterSpecInfo_StorageInfo) GetTypeID() string {
	if m != nil {
		return m.TypeID
	}
	return ""
}

func (m *ClusterProfile_ClusterSpecInfo_StorageInfo) GetStorageCapacity() int64 {
	if m != nil {
		return m.StorageCapacity
	}
	return 0
}

// Message from ResourceCollector, Cluster Controller should get response from ResourceCollector.
type ReturnMessageClusterProfile struct {
	ClusterNameSpace     string                               `protobuf:"bytes,1,opt,name=ClusterNameSpace,proto3" json:"ClusterNameSpace,omitempty"`
	ClusterName          string                               `protobuf:"bytes,2,opt,name=ClusterName,proto3" json:"ClusterName,omitempty"`
	ReturnCode           ReturnMessageClusterProfile_CodeType `protobuf:"varint,3,opt,name=ReturnCode,proto3,enum=proto.ReturnMessageClusterProfile_CodeType" json:"ReturnCode,omitempty"`
	Message              string                               `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *ReturnMessageClusterProfile) Reset()         { *m = ReturnMessageClusterProfile{} }
func (m *ReturnMessageClusterProfile) String() string { return proto.CompactTextString(m) }
func (*ReturnMessageClusterProfile) ProtoMessage()    {}
func (*ReturnMessageClusterProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_f471dfbba0a766f3, []int{1}
}
func (m *ReturnMessageClusterProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnMessageClusterProfile.Unmarshal(m, b)
}
func (m *ReturnMessageClusterProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnMessageClusterProfile.Marshal(b, m, deterministic)
}
func (dst *ReturnMessageClusterProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnMessageClusterProfile.Merge(dst, src)
}
func (m *ReturnMessageClusterProfile) XXX_Size() int {
	return xxx_messageInfo_ReturnMessageClusterProfile.Size(m)
}
func (m *ReturnMessageClusterProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnMessageClusterProfile.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnMessageClusterProfile proto.InternalMessageInfo

func (m *ReturnMessageClusterProfile) GetClusterNameSpace() string {
	if m != nil {
		return m.ClusterNameSpace
	}
	return ""
}

func (m *ReturnMessageClusterProfile) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *ReturnMessageClusterProfile) GetReturnCode() ReturnMessageClusterProfile_CodeType {
	if m != nil {
		return m.ReturnCode
	}
	return ReturnMessageClusterProfile_Error
}

func (m *ReturnMessageClusterProfile) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ClusterProfile)(nil), "proto.ClusterProfile")
	proto.RegisterType((*ClusterProfile_ClusterSpecInfo)(nil), "proto.ClusterProfile.ClusterSpecInfo")
	proto.RegisterType((*ClusterProfile_ClusterSpecInfo_GeoLocationInfo)(nil), "proto.ClusterProfile.ClusterSpecInfo.GeoLocationInfo")
	proto.RegisterType((*ClusterProfile_ClusterSpecInfo_RegionInfo)(nil), "proto.ClusterProfile.ClusterSpecInfo.RegionInfo")
	proto.RegisterType((*ClusterProfile_ClusterSpecInfo_OperatorInfo)(nil), "proto.ClusterProfile.ClusterSpecInfo.OperatorInfo")
	proto.RegisterType((*ClusterProfile_ClusterSpecInfo_FlavorInfo)(nil), "proto.ClusterProfile.ClusterSpecInfo.FlavorInfo")
	proto.RegisterType((*ClusterProfile_ClusterSpecInfo_StorageInfo)(nil), "proto.ClusterProfile.ClusterSpecInfo.StorageInfo")
	proto.RegisterType((*ReturnMessageClusterProfile)(nil), "proto.ReturnMessageClusterProfile")
	proto.RegisterEnum("proto.ReturnMessageClusterProfile_CodeType", ReturnMessageClusterProfile_CodeType_name, ReturnMessageClusterProfile_CodeType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClusterProtocolClient is the client API for ClusterProtocol service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClusterProtocolClient interface {
	SendClusterProfile(ctx context.Context, in *ClusterProfile, opts ...grpc.CallOption) (*ReturnMessageClusterProfile, error)
}

type clusterProtocolClient struct {
	cc *grpc.ClientConn
}

func NewClusterProtocolClient(cc *grpc.ClientConn) ClusterProtocolClient {
	return &clusterProtocolClient{cc}
}

func (c *clusterProtocolClient) SendClusterProfile(ctx context.Context, in *ClusterProfile, opts ...grpc.CallOption) (*ReturnMessageClusterProfile, error) {
	out := new(ReturnMessageClusterProfile)
	err := c.cc.Invoke(ctx, "/proto.ClusterProtocol/SendClusterProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterProtocolServer is the server API for ClusterProtocol service.
type ClusterProtocolServer interface {
	SendClusterProfile(context.Context, *ClusterProfile) (*ReturnMessageClusterProfile, error)
}

func RegisterClusterProtocolServer(s *grpc.Server, srv ClusterProtocolServer) {
	s.RegisterService(&_ClusterProtocol_serviceDesc, srv)
}

func _ClusterProtocol_SendClusterProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterProfile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterProtocolServer).SendClusterProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ClusterProtocol/SendClusterProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterProtocolServer).SendClusterProfile(ctx, req.(*ClusterProfile))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClusterProtocol_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ClusterProtocol",
	HandlerType: (*ClusterProtocolServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendClusterProfile",
			Handler:    _ClusterProtocol_SendClusterProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster.proto",
}

func init() { proto.RegisterFile("cluster.proto", fileDescriptor_cluster_f471dfbba0a766f3) }

var fileDescriptor_cluster_f471dfbba0a766f3 = []byte{
	// 662 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xdd, 0x6a, 0xdb, 0x4c,
	0x10, 0x8d, 0xf3, 0xe3, 0xd8, 0xa3, 0xfc, 0x98, 0x85, 0xef, 0x43, 0xa8, 0x14, 0x8c, 0x69, 0x8b,
	0x49, 0xc1, 0x6e, 0xdd, 0x1f, 0x7a, 0x9b, 0x3a, 0x69, 0x12, 0xd2, 0x24, 0xae, 0x9c, 0x52, 0xc8,
	0xdd, 0x5a, 0x9e, 0x38, 0x22, 0xb2, 0x56, 0xac, 0xd6, 0x06, 0x3f, 0x54, 0x1f, 0xae, 0x0f, 0x50,
	0x28, 0xbb, 0xab, 0xdd, 0xac, 0x95, 0xd2, 0xfa, 0xa6, 0x57, 0xd6, 0x1c, 0x9d, 0x39, 0x33, 0xb3,
	0x73, 0x56, 0x86, 0xdd, 0x28, 0x99, 0xe5, 0x02, 0x79, 0x27, 0xe3, 0x4c, 0x30, 0xb2, 0xa5, 0x7e,
	0x5a, 0x3f, 0xeb, 0xb0, 0xd7, 0xd7, 0x2f, 0x06, 0x9c, 0xdd, 0xc6, 0x09, 0x92, 0x03, 0x68, 0x14,
	0xc8, 0x25, 0x9d, 0xe2, 0x30, 0xa3, 0x11, 0xfa, 0x95, 0x66, 0xa5, 0x5d, 0x0f, 0x1f, 0xe1, 0xa4,
	0x09, 0x9e, 0x83, 0xf9, 0xeb, 0x8a, 0xe6, 0x42, 0xe4, 0xc4, 0x32, 0x86, 0x19, 0x46, 0xfe, 0x46,
	0xb3, 0xd2, 0xf6, 0x7a, 0xcf, 0x75, 0x13, 0x9d, 0xe5, 0xca, 0x1d, 0x87, 0x78, 0x96, 0xde, 0xb2,
	0xd0, 0xcd, 0x24, 0xcf, 0x60, 0xd7, 0x84, 0x82, 0x8a, 0x59, 0xee, 0x6f, 0xaa, 0x62, 0xcb, 0x60,
	0xf0, 0xbd, 0x06, 0xfb, 0x25, 0x19, 0x67, 0xa0, 0xb3, 0xec, 0x70, 0x3c, 0xe6, 0x98, 0xe7, 0xa5,
	0x81, 0x2c, 0x4e, 0xbe, 0x81, 0x77, 0x82, 0xec, 0x33, 0x8b, 0xa8, 0x88, 0x59, 0xaa, 0x06, 0xf2,
	0x7a, 0xef, 0x56, 0x6a, 0xb7, 0xe3, 0x24, 0xea, 0xf6, 0x1d, 0x80, 0x9c, 0x42, 0x35, 0xc4, 0x89,
	0xd4, 0xd4, 0x47, 0xf0, 0x6a, 0x35, 0x4d, 0x9d, 0xa3, 0xe4, 0x8a, 0x7c, 0x72, 0x09, 0xb5, 0xab,
	0x0c, 0x39, 0x15, 0x8c, 0xab, 0x33, 0xf0, 0x7a, 0xbd, 0xd5, 0xb4, 0x4c, 0x96, 0x52, 0xb3, 0x1a,
	0xb2, 0xb3, 0x4f, 0x09, 0x9d, 0x33, 0xee, 0x6f, 0x35, 0x37, 0x56, 0xef, 0x4c, 0xe7, 0xe8, 0xce,
	0xf4, 0x33, 0x39, 0x87, 0xed, 0xa1, 0x60, 0x9c, 0x4e, 0xd0, 0xaf, 0x2a, 0xa9, 0xd7, 0xab, 0x49,
	0x15, 0x49, 0x4a, 0xcb, 0x28, 0x48, 0x6b, 0x1d, 0xc7, 0x59, 0x9f, 0x66, 0x34, 0x8a, 0xc5, 0xc2,
	0xdf, 0x6e, 0x56, 0xda, 0x1b, 0xa1, 0x0b, 0x29, 0xf3, 0x0d, 0xbe, 0x5a, 0x46, 0x4d, 0x33, 0x1c,
	0x48, 0x32, 0x2e, 0x70, 0x6a, 0x19, 0x75, 0xcd, 0x70, 0x20, 0xc9, 0x18, 0x22, 0x9f, 0xcb, 0xde,
	0xe2, 0x08, 0x7d, 0xd0, 0x0c, 0x07, 0x92, 0xbe, 0x3b, 0x65, 0x53, 0x1c, 0x46, 0x77, 0x38, 0x9e,
	0x25, 0xc8, 0x7d, 0x4f, 0xfb, 0x6e, 0x09, 0x24, 0x2f, 0x60, 0x4f, 0x02, 0x47, 0x71, 0x9e, 0x51,
	0x11, 0xdd, 0x21, 0xf7, 0x77, 0x14, 0xad, 0x84, 0x06, 0x0c, 0xf6, 0x4b, 0x36, 0x21, 0x04, 0x36,
	0xfb, 0xb2, 0x3b, 0x6d, 0x49, 0xf5, 0x4c, 0x02, 0xa8, 0x0d, 0x38, 0x9b, 0xc7, 0x69, 0x64, 0x2e,
	0x95, 0x8d, 0x25, 0xff, 0x90, 0x23, 0x55, 0x3e, 0xaa, 0x87, 0xea, 0x99, 0xf8, 0xb0, 0xdd, 0x67,
	0xb3, 0x54, 0xf0, 0x45, 0x71, 0x2d, 0x4c, 0x18, 0x0c, 0x00, 0x1e, 0x3c, 0x44, 0xfe, 0xb7, 0x2e,
	0xd4, 0xd5, 0x8c, 0xa7, 0x0e, 0xa0, 0x71, 0x38, 0xa7, 0x71, 0x42, 0x47, 0x71, 0x12, 0x8b, 0xc5,
	0x0d, 0x4b, 0x4d, 0xdd, 0x47, 0x78, 0x70, 0x00, 0x3b, 0xae, 0x93, 0x64, 0xaf, 0xd6, 0x8f, 0x5a,
	0xd5, 0xc6, 0xc1, 0x25, 0xc0, 0x83, 0x4f, 0x24, 0xb3, 0x88, 0x8e, 0x0c, 0xd3, 0xc4, 0xf2, 0x98,
	0xaf, 0x99, 0xa0, 0x89, 0x5d, 0xd6, 0xba, 0x5a, 0xc5, 0x32, 0x18, 0x5c, 0x81, 0xe7, 0x98, 0x45,
	0x8e, 0x73, 0xbd, 0xc8, 0xd0, 0xca, 0x15, 0x11, 0x69, 0xc3, 0x7e, 0x41, 0x2b, 0xc9, 0x95, 0xe1,
	0xd6, 0x8f, 0x0a, 0x3c, 0x09, 0x51, 0xcc, 0x78, 0x7a, 0x81, 0x79, 0x2e, 0xdf, 0xfc, 0xcb, 0x8f,
	0xe1, 0xb9, 0x5c, 0x86, 0x2c, 0xd6, 0x67, 0x63, 0x54, 0x0b, 0xdc, 0xeb, 0xbd, 0x2c, 0xee, 0xc8,
	0x1f, 0xba, 0xe8, 0x48, 0xba, 0x1c, 0x2d, 0x74, 0xd2, 0xe5, 0xce, 0x0b, 0xb6, 0xd9, 0x79, 0x11,
	0xb6, 0x9e, 0x42, 0xcd, 0x64, 0x90, 0x3a, 0x6c, 0x1d, 0x73, 0xce, 0x78, 0x63, 0x8d, 0x54, 0x61,
	0xfd, 0xea, 0xbc, 0x51, 0xe9, 0x8d, 0xed, 0x27, 0x72, 0x20, 0x2b, 0x47, 0x2c, 0x21, 0x5f, 0x80,
	0x0c, 0x31, 0x1d, 0x97, 0x86, 0xff, 0xef, 0xb7, 0xd7, 0x37, 0x68, 0xfd, 0xbd, 0xe3, 0xd6, 0xda,
	0xc7, 0xf7, 0x37, 0x6f, 0xef, 0x3f, 0xe4, 0x9d, 0x98, 0x75, 0xef, 0x67, 0x23, 0xe4, 0x29, 0x0a,
	0xcc, 0xbb, 0x93, 0x84, 0x8d, 0x68, 0x92, 0x9b, 0x6b, 0xd3, 0x9d, 0xf0, 0x2c, 0xea, 0x16, 0x7f,
	0x4c, 0x5d, 0xa5, 0x3a, 0xaa, 0xaa, 0x9f, 0x37, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x5a,
	0x1b, 0xcd, 0xb0, 0x06, 0x00, 0x00,
}
