// Code generated by protoc-gen-go. DO NOT EDIT.
// source: clusterstate.proto

package cluster // import "k8s.io/kubernetes/globalscheduler/grpc/cluster"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClusterState struct {
	NameSpace            string   `protobuf:"bytes,1,opt,name=NameSpace,proto3" json:"NameSpace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	State                int32    `protobuf:"varint,3,opt,name=State,proto3" json:"State,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterState) Reset()         { *m = ClusterState{} }
func (m *ClusterState) String() string { return proto.CompactTextString(m) }
func (*ClusterState) ProtoMessage()    {}
func (*ClusterState) Descriptor() ([]byte, []int) {
	return fileDescriptor_clusterstate_eeef83e8bbed3545, []int{0}
}
func (m *ClusterState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterState.Unmarshal(m, b)
}
func (m *ClusterState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterState.Marshal(b, m, deterministic)
}
func (dst *ClusterState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterState.Merge(dst, src)
}
func (m *ClusterState) XXX_Size() int {
	return xxx_messageInfo_ClusterState.Size(m)
}
func (m *ClusterState) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterState.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterState proto.InternalMessageInfo

func (m *ClusterState) GetNameSpace() string {
	if m != nil {
		return m.NameSpace
	}
	return ""
}

func (m *ClusterState) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClusterState) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

// message from ClusterController
type ReturnMessage struct {
	NameSpace            string   `protobuf:"bytes,1,opt,name=NameSpace,proto3" json:"NameSpace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	ReturnCode           int32    `protobuf:"varint,3,opt,name=ReturnCode,proto3" json:"ReturnCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnMessage) Reset()         { *m = ReturnMessage{} }
func (m *ReturnMessage) String() string { return proto.CompactTextString(m) }
func (*ReturnMessage) ProtoMessage()    {}
func (*ReturnMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_clusterstate_eeef83e8bbed3545, []int{1}
}
func (m *ReturnMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnMessage.Unmarshal(m, b)
}
func (m *ReturnMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnMessage.Marshal(b, m, deterministic)
}
func (dst *ReturnMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnMessage.Merge(dst, src)
}
func (m *ReturnMessage) XXX_Size() int {
	return xxx_messageInfo_ReturnMessage.Size(m)
}
func (m *ReturnMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnMessage proto.InternalMessageInfo

func (m *ReturnMessage) GetNameSpace() string {
	if m != nil {
		return m.NameSpace
	}
	return ""
}

func (m *ReturnMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReturnMessage) GetReturnCode() int32 {
	if m != nil {
		return m.ReturnCode
	}
	return 0
}

func init() {
	proto.RegisterType((*ClusterState)(nil), "proto.ClusterState")
	proto.RegisterType((*ReturnMessage)(nil), "proto.ReturnMessage")
}

func init() { proto.RegisterFile("clusterstate.proto", fileDescriptor_clusterstate_eeef83e8bbed3545) }

var fileDescriptor_clusterstate_eeef83e8bbed3545 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x50, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x25, 0x40, 0x90, 0x7a, 0x82, 0xc5, 0xed, 0x10, 0x10, 0x82, 0x2a, 0x53, 0x27, 0x47, 0x82,
	0x85, 0x39, 0x99, 0x41, 0x55, 0x2a, 0x18, 0x58, 0x90, 0xe3, 0x9c, 0x42, 0x55, 0xd3, 0x8b, 0x7c,
	0xf6, 0xff, 0xa3, 0xd8, 0x89, 0x08, 0x8c, 0x4c, 0xf6, 0xbd, 0xa7, 0xf7, 0xee, 0xde, 0x03, 0xa1,
	0x8d, 0x67, 0x87, 0x96, 0x9d, 0x72, 0x28, 0x7b, 0x4b, 0x8e, 0x44, 0x1a, 0x9e, 0xfc, 0x0d, 0x2e,
	0xab, 0x48, 0xee, 0x06, 0x52, 0xdc, 0xc2, 0xe2, 0x45, 0x7d, 0xe1, 0xae, 0x57, 0x1a, 0xb3, 0x64,
	0x9d, 0x6c, 0x16, 0xf5, 0x0f, 0x20, 0x04, 0x9c, 0x0f, 0x43, 0x76, 0x1a, 0x88, 0xf0, 0x17, 0x2b,
	0x48, 0x83, 0x34, 0x3b, 0x5b, 0x27, 0x9b, 0xb4, 0x8e, 0x43, 0xae, 0xe0, 0xaa, 0x46, 0xe7, 0xed,
	0xf1, 0x19, 0x99, 0x55, 0xf7, 0x1f, 0xe3, 0x3b, 0x80, 0x68, 0x51, 0x51, 0x3b, 0xb9, 0xcf, 0x90,
	0x87, 0x0f, 0xb8, 0xae, 0x91, 0xc9, 0x5b, 0x8d, 0x15, 0x19, 0x83, 0xda, 0x91, 0xdd, 0x0e, 0xa1,
	0x34, 0x19, 0x51, 0xc2, 0xf2, 0xb5, 0x6f, 0x95, 0xc3, 0x59, 0x3a, 0xcf, 0x62, 0x19, 0xd3, 0xcb,
	0x79, 0xe6, 0x9b, 0xd5, 0x08, 0xfe, 0x3a, 0x38, 0x3f, 0x29, 0x15, 0xdc, 0xef, 0x49, 0x76, 0x86,
	0x1a, 0x65, 0x58, 0x7f, 0x62, 0xeb, 0x0d, 0x5a, 0xd9, 0xd9, 0x5e, 0xcb, 0xb1, 0xd0, 0x72, 0x2a,
	0x2f, 0xec, 0xdd, 0x26, 0xef, 0xf2, 0xf0, 0xc4, 0x72, 0x4f, 0xc5, 0xc1, 0x37, 0x68, 0x8f, 0xe8,
	0x90, 0x8b, 0x3f, 0xfa, 0x62, 0xd0, 0x17, 0xa3, 0xbe, 0xb9, 0x08, 0x9b, 0x1f, 0xbf, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xcb, 0x27, 0xf2, 0x41, 0xa2, 0x01, 0x00, 0x00,
}
