/*
Copyright 2020 Authors of Arktos.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	distributorv1 "k8s.io/kubernetes/globalscheduler/pkg/apis/distributor/v1"
)

// FakeDistributors implements DistributorInterface
type FakeDistributors struct {
	Fake *FakeGlobalschedulerV1
	ns   string
	te   string
}

var distributorsResource = schema.GroupVersionResource{Group: "globalscheduler.com", Version: "v1", Resource: "distributors"}

var distributorsKind = schema.GroupVersionKind{Group: "globalscheduler.com", Version: "v1", Kind: "Distributor"}

// Get takes name of the distributor, and returns the corresponding distributor object, and an error if there is any.
func (c *FakeDistributors) Get(name string, options v1.GetOptions) (result *distributorv1.Distributor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithMultiTenancy(distributorsResource, c.ns, name, c.te), &distributorv1.Distributor{})

	if obj == nil {
		return nil, err
	}

	return obj.(*distributorv1.Distributor), err
}

// List takes label and field selectors, and returns the list of Distributors that match those selectors.
func (c *FakeDistributors) List(opts v1.ListOptions) (result *distributorv1.DistributorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithMultiTenancy(distributorsResource, distributorsKind, c.ns, opts, c.te), &distributorv1.DistributorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &distributorv1.DistributorList{ListMeta: obj.(*distributorv1.DistributorList).ListMeta}
	for _, item := range obj.(*distributorv1.DistributorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.AggregatedWatchInterface that watches the requested distributors.
func (c *FakeDistributors) Watch(opts v1.ListOptions) watch.AggregatedWatchInterface {
	aggWatch := watch.NewAggregatedWatcher()
	watcher, err := c.Fake.
		InvokesWatch(testing.NewWatchActionWithMultiTenancy(distributorsResource, c.ns, opts, c.te))

	aggWatch.AddWatchInterface(watcher, err)
	return aggWatch
}

// Create takes the representation of a distributor and creates it.  Returns the server's representation of the distributor, and an error, if there is any.
func (c *FakeDistributors) Create(distributor *distributorv1.Distributor) (result *distributorv1.Distributor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithMultiTenancy(distributorsResource, c.ns, distributor, c.te), &distributorv1.Distributor{})

	if obj == nil {
		return nil, err
	}

	return obj.(*distributorv1.Distributor), err
}

// Update takes the representation of a distributor and updates it. Returns the server's representation of the distributor, and an error, if there is any.
func (c *FakeDistributors) Update(distributor *distributorv1.Distributor) (result *distributorv1.Distributor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithMultiTenancy(distributorsResource, c.ns, distributor, c.te), &distributorv1.Distributor{})

	if obj == nil {
		return nil, err
	}

	return obj.(*distributorv1.Distributor), err
}

// Delete takes name of the distributor and deletes it. Returns an error if one occurs.
func (c *FakeDistributors) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithMultiTenancy(distributorsResource, c.ns, name, c.te), &distributorv1.Distributor{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDistributors) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithMultiTenancy(distributorsResource, c.ns, listOptions, c.te)

	_, err := c.Fake.Invokes(action, &distributorv1.DistributorList{})
	return err
}

// Patch applies the patch and returns the patched distributor.
func (c *FakeDistributors) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *distributorv1.Distributor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithMultiTenancy(distributorsResource, c.te, c.ns, name, pt, data, subresources...), &distributorv1.Distributor{})

	if obj == nil {
		return nil, err
	}

	return obj.(*distributorv1.Distributor), err
}
