/*
Copyright 2020 Authors of Arktos.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	dispatcherv1 "k8s.io/kubernetes/globalscheduler/pkg/apis/dispatcher/v1"
)

// FakeDispatchers implements DispatcherInterface
type FakeDispatchers struct {
	Fake *FakeGlobalschedulerV1
	ns   string
	te   string
}

var dispatchersResource = schema.GroupVersionResource{Group: "globalscheduler.com", Version: "v1", Resource: "dispatchers"}

var dispatchersKind = schema.GroupVersionKind{Group: "globalscheduler.com", Version: "v1", Kind: "Dispatcher"}

// Get takes name of the dispatcher, and returns the corresponding dispatcher object, and an error if there is any.
func (c *FakeDispatchers) Get(name string, options v1.GetOptions) (result *dispatcherv1.Dispatcher, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithMultiTenancy(dispatchersResource, c.ns, name, c.te), &dispatcherv1.Dispatcher{})

	if obj == nil {
		return nil, err
	}

	return obj.(*dispatcherv1.Dispatcher), err
}

// List takes label and field selectors, and returns the list of Dispatchers that match those selectors.
func (c *FakeDispatchers) List(opts v1.ListOptions) (result *dispatcherv1.DispatcherList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithMultiTenancy(dispatchersResource, dispatchersKind, c.ns, opts, c.te), &dispatcherv1.DispatcherList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &dispatcherv1.DispatcherList{ListMeta: obj.(*dispatcherv1.DispatcherList).ListMeta}
	for _, item := range obj.(*dispatcherv1.DispatcherList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.AggregatedWatchInterface that watches the requested dispatchers.
func (c *FakeDispatchers) Watch(opts v1.ListOptions) watch.AggregatedWatchInterface {
	aggWatch := watch.NewAggregatedWatcher()
	watcher, err := c.Fake.
		InvokesWatch(testing.NewWatchActionWithMultiTenancy(dispatchersResource, c.ns, opts, c.te))

	aggWatch.AddWatchInterface(watcher, err)
	return aggWatch
}

// Create takes the representation of a dispatcher and creates it.  Returns the server's representation of the dispatcher, and an error, if there is any.
func (c *FakeDispatchers) Create(dispatcher *dispatcherv1.Dispatcher) (result *dispatcherv1.Dispatcher, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithMultiTenancy(dispatchersResource, c.ns, dispatcher, c.te), &dispatcherv1.Dispatcher{})

	if obj == nil {
		return nil, err
	}

	return obj.(*dispatcherv1.Dispatcher), err
}

// Update takes the representation of a dispatcher and updates it. Returns the server's representation of the dispatcher, and an error, if there is any.
func (c *FakeDispatchers) Update(dispatcher *dispatcherv1.Dispatcher) (result *dispatcherv1.Dispatcher, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithMultiTenancy(dispatchersResource, c.ns, dispatcher, c.te), &dispatcherv1.Dispatcher{})

	if obj == nil {
		return nil, err
	}

	return obj.(*dispatcherv1.Dispatcher), err
}

// Delete takes name of the dispatcher and deletes it. Returns an error if one occurs.
func (c *FakeDispatchers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithMultiTenancy(dispatchersResource, c.ns, name, c.te), &dispatcherv1.Dispatcher{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDispatchers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithMultiTenancy(dispatchersResource, c.ns, listOptions, c.te)

	_, err := c.Fake.Invokes(action, &dispatcherv1.DispatcherList{})
	return err
}

// Patch applies the patch and returns the patched dispatcher.
func (c *FakeDispatchers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *dispatcherv1.Dispatcher, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithMultiTenancy(dispatchersResource, c.te, c.ns, name, pt, data, subresources...), &dispatcherv1.Dispatcher{})

	if obj == nil {
		return nil, err
	}

	return obj.(*dispatcherv1.Dispatcher), err
}
